# Generated by Django 4.1.6 on 2023-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ID_Image', models.ImageField(upload_to='uploads/')),
                ('ID_Number', models.CharField(default='GHAXXXXXX', max_length=100)),
                ('Signature', models.BooleanField(default=False)),
                ('Guarantor_Name', models.CharField(max_length=100)),
                ('Generator_ID', models.ImageField(upload_to='uploads/')),
                ('Guarantor_ID_Number', models.CharField(default='GHAXXXXXX', max_length=30)),
                ('Pre_Contract_Agreement', models.TextField(default='I,.............................................. agree that if my loan application is successful, the following will apply to a. Intrest shall be ____% per month/annum-flat/reducing /n b. Loan shall subject a full repayment on demand at any time /n c. I event of any default, a penal intrest Rate of 2% per month shall be applied above /n 1. Early payment of loan is permitted to subject replacement of outstanding principal amount defaults in making two installment repayment', max_length=100000)),
                ('Upload_Contract_agreement_Form', models.ImageField(upload_to='uploads/')),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GuarantorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relationship_with_Applicant', models.CharField(default='Co Worker, Emlpoyer, Friend, Relatives', max_length=10)),
                ('Surname', models.CharField(max_length=100)),
                ('FirstName', models.TextField(max_length=999)),
                ('OtherName', models.CharField(max_length=20)),
                ('Profession', models.CharField(max_length=30)),
                ('Position', models.CharField(max_length=30)),
                ('ResidentialStatus', models.CharField(max_length=11)),
                ('HouseNumber', models.CharField(max_length=20)),
                ('DigitalAddress', models.TextField(default='cx-152-521 or Pt189/16', max_length=11)),
                ('NearestLandMark', models.CharField(default='Kasoa Marketplace', max_length=999)),
                ('MobileNumber', models.CharField(default='+233000000000', max_length=15)),
                ('Email', models.EmailField(blank=True, default='joy@gmail.com', max_length=254)),
                ('Gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('DateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Loan_Amount', models.FloatField()),
                ('Purpose', models.TextField()),
                ('Loan_Duration_Period', models.CharField(default='3months, 4months, 5months, 6months, 24months, Others', max_length=99)),
                ('Mode_Of_Payment', models.TextField(default='post dated check, Ach direct Mandate, Cash, Momo')),
                ('Proffered_Repayment_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=100)),
                ('FirstName', models.TextField(max_length=999)),
                ('OtherName', models.CharField(max_length=20)),
                ('Gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('MaritalStatus', models.CharField(max_length=20)),
                ('Profession', models.CharField(max_length=30)),
                ('TotalChildren', models.IntegerField()),
                ('ResidentialStatus', models.CharField(max_length=11)),
                ('HouseNumber', models.CharField(max_length=20)),
                ('DigitalAddress', models.TextField(default='cx-152-521 or Pt189/16', max_length=11)),
                ('NearestLandMark', models.CharField(default='Kasoa Marketplace', max_length=999)),
                ('MobileNumber', models.CharField(default='+233000000000', max_length=15)),
                ('Email', models.EmailField(blank=True, default='joy@gmail.com', max_length=254)),
                ('Religion', models.CharField(default='Christian Religion', max_length=100)),
                ('ReligiousLeaderNameAndNumber', models.CharField(default='Name +23300000000', max_length=100)),
                ('DateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SpouseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('SpouseName', models.CharField(max_length=11)),
                ('Profession', models.CharField(max_length=11)),
                ('Position', models.CharField(max_length=11)),
                ('Mobile', models.CharField(max_length=11)),
                ('Proffered_Repayment_Date', models.DateTimeField()),
            ],
        ),
    ]
