# Generated by Django 4.1.6 on 2023-02-09 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('color', models.CharField(default='Unknown', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)])),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'VehicleTypes',
                'db_table': 'VehicleType',
            },
        ),
        migrations.CreateModel(
            name='VehicleSale',
            fields=[
                ('invoice_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vehicletype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SMS.vehicletype', verbose_name='VehicleTypes')),
            ],
            options={
                'verbose_name_plural': 'VehicleSales',
                'db_table': 'VehicleSales',
                'ordering': ('invoice_id',),
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('invoice', models.ManyToManyField(blank=True, to='SMS.vehiclesale')),
            ],
            options={
                'verbose_name_plural': 'Owners',
                'db_table': 'Owner',
            },
        ),
    ]
