# Generated by Django 4.1.6 on 2023-02-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSale',
            fields=[
                ('invoice_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'IInvoiceSales',
                'db_table': 'InvoiceSales',
                'ordering': ('invoice_id',),
            },
        ),
        migrations.AlterModelOptions(
            name='invoicetype',
            options={'verbose_name_plural': 'InvoiceTypes'},
        ),
        migrations.AlterModelTable(
            name='invoicetype',
            table='InvoiceType',
        ),
        migrations.RenameModel(
            old_name='VehicleType',
            new_name='InvoiceType',
        ),
        migrations.DeleteModel(
            name='VehicleSale',
        ),
        migrations.AddField(
            model_name='invoicesale',
            name='Invoice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SMS.invoicetype', verbose_name='InvoiceTypes'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='invoice',
            field=models.ManyToManyField(blank=True, to='SMS.invoicesale'),
        ),
    ]
